name: Documentation

on:
  release:
    types: [published]

jobs:
  deploy_docs:
    name: Deploy Documentation
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Generate Documentation
        run: |
          sed  -i.bak "s/title:\(.*\)/title:\1 (${{ github.ref }})/g" .jazzy.yaml
          bundle exec jazzy

      - name: Fix Invalid URLs
        run: |
          cd docs
          touch .nojekyll

      - name: Commit files
        run: |
          cd docs
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Deploying Updated Jazzy Docs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
