name: Documentation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*.*.*"

jobs:
  deploy_docs:
    name: Generate Documentation
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Generate Documentation
        run: |
          ESCAPED_REF_NAME=$(echo "${{ github.ref }}" | sed 's/[\/&]/\\&/g')
          sed  -i.bak "s/title:\(.*\)/title:\1 ($ESCAPED_REF_NAME)/g" .jazzy.yaml

          SDK_PATH=`xcrun --sdk iphonesimulator --show-sdk-path`
          SDK_VERSION=`xcrun --sdk iphonesimulator --show-sdk-version`
          bundle exec jazzy \
            -c .jazzy.yaml \
            --build-tool-arguments "--sdk,${SDK_PATH},-Xswiftc,-sdk,-Xswiftc,$SDK_PATH,-Xswiftc,-target,-Xswiftc,arm64-apple-ios${SDK_VERSION}-simulator"

      - name: Fix Invalid URLs
        run: |
          cd docs
          touch .nojekyll

      - name: Commit files
        if: github.event_name == 'push'
        run: |
          cd docs
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Deploying Updated Jazzy Docs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.event_name == 'push'
        with:
          directory: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
