name: Publish Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publicsh-release:
    name: Publish Release
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
