name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  publicsh-release:
    name: Publish Release
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2.3.0

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            OnLaunch-iOS-Client.sha256
            OnLaunch-iOS-Client.zip
